'use client'

import { useState, useEffect } from 'react'
import { useSearchParams, useRouter } from 'next/navigation'
import { useUser } from '../../contexts/UserContext'

export default function ReportContent() {
  const [reportData, setReportData] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const searchParams = useSearchParams()
  const router = useRouter()
  const { user, getUserAnalyses, getLatestAnalysis } = useUser()
  const analysisId = searchParams.get('id')

  const loadReportData = () => {
    try {
      setLoading(true)

      let targetAnalysis = null

      if (user) {
        // Logged-in: pull from context
        const userAnalyses = getUserAnalyses()
        if (analysisId) {
          targetAnalysis = userAnalyses.find((analysis) => analysis.id === analysisId)
        } else {
          targetAnalysis = getLatestAnalysis()
        }
      } else {
        // Guest: use localStorage fallback
        const lastAnalysis = localStorage.getItem('skinai_last_analysis')
        if (lastAnalysis) {
          targetAnalysis = JSON.parse(lastAnalysis)
        }
      }

      if (!targetAnalysis) {
        setError('No analysis found. Please upload an image first.')
        return
      }

      const formattedReport = {
        id: targetAnalysis.id || Date.now().toString(),
        patientName: user ? user.name : 'Guest User',
        patientEmail: user ? user.email : 'N/A',
        accountType: user ? user.accountType : 'guest',
        analysisDate: new Date(targetAnalysis.timestamp || targetAnalysis.ts).toLocaleDateString(),
        analysisTime: new Date(targetAnalysis.timestamp || targetAnalysis.ts).toLocaleTimeString(),
        ...targetAnalysis,
      }

      setReportData(formattedReport)
    } catch (err) {
      console.error('Error loading report:', err)
      setError('Failed to load report data')
    } finally {
      setLoading(false)
    }
  }

  const downloadReport = () => {
    if (!reportData) return

    const reportContent = generateReportContent(reportData)
    const blob = new Blob([reportContent], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `skinai-report-${reportData.id}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const generateReportContent = (data) => {
    return `
SKINAI ANALYSIS REPORT
=====================

PATIENT INFORMATION
==================
Name: ${data.patientName}
Email: ${data.patientEmail}
Account Type: ${data.accountType.toUpperCase()}
Analysis Date: ${data.analysisDate}
Analysis Time: ${data.analysisTime}
Report ID: ${data.id}

ANALYSIS RESULTS
===============
Uploaded File: ${data.fileName || 'N/A'}
File Size: ${data.fileSize ? (data.fileSize / 1024 / 1024).toFixed(2) + ' MB' : 'N/A'}
Condition Detected: ${data.skinCondition}
Severity Level: ${data.severity}
Confidence Score: ${data.confidence}%

AFFECTED AREAS ANALYSIS
======================
${data.affectedAreas ? data.affectedAreas.map(area => 
  `${area.area}: ${area.severity} severity (${area.percentage}% coverage)`
).join('\n') : 'No detailed area analysis available'}

TREATMENT RECOMMENDATIONS
========================
${data.recommendations ? data.recommendations.map((rec, index) => 
  `${index + 1}. ${rec}`
).join('\n') : 'No recommendations available'}

TREATMENT PLAN
=============
${data.treatmentPlan ? Object.entries(data.treatmentPlan).map(([phase, description]) => 
  `${phase.toUpperCase()}: ${description}`
).join('\n') : 'No treatment plan available'}

DISCLAIMER
==========
This report is generated by AI analysis and should not replace professional medical advice.
Please consult with a qualified dermatologist for proper diagnosis and treatment.

Generated: ${new Date().toLocaleString()}
Generated by: SkinAI Analysis System
    `.trim()
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
          <p className="mt-4 text-gray-600">Loading your report...</p>
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="text-red-500 text-xl mb-4">⚠️</div>
          <h2 className="text-xl font-semibold text-gray-900 mb-2">Report Not Found</h2>
          <p className="text-gray-600 mb-4">{error}</p>
          <div className="space-x-4">
            <button 
              onClick={() => router.push('/upload')}
              className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700"
            >
              Upload New Image
            </button>
            <button 
              onClick={() => router.push('/analysis')}
              className="bg-gray-600 text-white px-4 py-2 rounded-lg hover:bg-gray-700"
            >
              View History
            </button>
          </div>
        </div>
      </div>
    )
  }

  if (!reportData) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="text-gray-400 text-xl mb-4">📄</div>
          <h2 className="text-xl font-semibold text-gray-900 mb-2">No Report Data</h2>
          <p className="text-gray-600 mb-4">Unable to load report information</p>
          <button 
            onClick={() => router.push('/upload')}
            className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700"
          >
            Upload New Image
          </button>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white shadow-sm border-b print:shadow-none">
        <div className="max-w-4xl mx-auto px-4 py-4">
          <div className="flex justify-between items-center">
            <div>
              <h1 className="text-2xl font-bold text-gray-900">Skin Analysis Report</h1>
              <p className="text-gray-600">
                Personal analysis for {reportData.patientName} • {reportData.analysisDate}
              </p>
            </div>
            <div className="flex gap-2 print:hidden">
              <button
                onClick={downloadReport}
                className="bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700 flex items-center gap-2"
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
                Download Report
              </button>
              <button
                onClick={() => window.print()}
                className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 flex items-center gap-2"
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
                </svg>
                Print Report
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Report Content */}
      <div className="max-w-4xl mx-auto px-4 py-8">
        <div className="bg-white rounded-lg shadow-sm border p-8 space-y-8">
          {/* Patient Information */}
          <div className="border-b pb-6">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">Patient Information</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <h3 className="text-sm font-medium text-gray-500">Patient Name</h3>
                <p className="text-lg font-semibold text-gray-900">{reportData.patientName}</p>
              </div>
              <div>
                <h3 className="text-sm font-medium text-gray-500">Email</h3>
                <p className="text-lg font-semibold text-gray-900">{reportData.patientEmail}</p>
              </div>
              <div>
                <h3 className="text-sm font-medium text-gray-500">Analysis Date</h3>
                <p className="text-lg font-semibold text-gray-900">{reportData.analysisDate}</p>
              </div>
              <div>
                <h3 className="text-sm font-medium text-gray-500">Account Type</h3>
                <p className="text-lg font-semibold text-gray-900 capitalize">{reportData.accountType}</p>
              </div>
            </div>
          </div>

          {/* Analysis Results */}
          <div>
            <h2 className="text-xl font-semibold text-gray-900 mb-4">Analysis Results</h2>
            <div className="bg-blue-50 rounded-lg p-6">
              <div className="flex items-center justify-between mb-4">
                <div>
                  <h3 className="text-lg font-medium text-blue-900">{reportData.skinCondition}</h3>
                  <p className="text-blue-700">Severity: {reportData.severity}</p>
                </div>
                <div className="text-right">
                  <div className="text-2xl font-bold text-blue-900">{reportData.confidence}%</div>
                  <div className="text-sm text-blue-700">Confidence</div>
                </div>
              </div>
              <div className="text-sm text-blue-600">
                <p>File: {reportData.fileName || 'N/A'}</p>
                <p>Size: {reportData.fileSize ? (reportData.fileSize / 1024 / 1024).toFixed(2) + ' MB' : 'N/A'}</p>
              </div>
            </div>
          </div>

          {/* Affected Areas */}
          {reportData.affectedAreas && reportData.affectedAreas.length > 0 && (
            <div>
              <h2 className="text-xl font-semibold text-gray-900 mb-4">Affected Areas Analysis</h2>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {reportData.affectedAreas.map((area, index) => (
                  <div key={index} className="bg-gray-50 rounded-lg p-4">
                    <div className="flex justify-between items-center mb-2">
                      <h3 className="font-medium text-gray-900">{area.area}</h3>
                      <span className={`px-2 py-1 rounded text-xs font-medium ${
                        area.severity === 'Mild' ? 'bg-green-100 text-green-800' :
                        area.severity === 'Moderate' ? 'bg-yellow-100 text-yellow-800' :
                        'bg-red-100 text-red-800'
                      }`}>
                        {area.severity}
                      </span>
                    </div>
                    <div className="text-sm text-gray-600">
                      Coverage: {area.percentage}%
                    </div>
                    <div className="w-full bg-gray-200 rounded-full h-2 mt-2">
                      <div 
                        className={`h-2 rounded-full ${
                          area.severity === 'Mild' ? 'bg-green-500' :
                          area.severity === 'Moderate' ? 'bg-yellow-500' :
                          'bg-red-500'
                        }`}
                        style={{ width: `${area.percentage}%` }}
                      ></div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Recommendations */}
          {reportData.recommendations && reportData.recommendations.length > 0 && (
            <div>
              <h2 className="text-xl font-semibold text-gray-900 mb-4">Treatment Recommendations</h2>
              <div className="bg-green-50 rounded-lg p-6">
                <ul className="space-y-3">
                  {reportData.recommendations.map((recommendation, index) => (
                    <li key={index} className="flex items-start gap-3">
                      <div className="flex-shrink-0 w-6 h-6 bg-green-100 rounded-full flex items-center justify-center mt-0.5">
                        <span className="text-green-600 text-sm font-medium">{index + 1}</span>
                      </div>
                      <p className="text-green-800">{recommendation}</p>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          )}

          {/* Treatment Plan */}
          {reportData.treatmentPlan && (
            <div>
              <h2 className="text-xl font-semibold text-gray-900 mb-4">Treatment Plan</h2>
              <div className="space-y-4">
                {Object.entries(reportData.treatmentPlan).map(([phase, description], index) => (
                  <div key={index} className="border-l-4 border-blue-500 pl-4">
                    <h3 className="font-medium text-gray-900 capitalize">{phase.replace(/([A-Z])/g, ' $1').trim()}</h3>
                    <p className="text-gray-600 mt-1">{description}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Disclaimer */}
          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-6">
            <div className="flex items-start gap-3">
              <div className="flex-shrink-0">
                <svg className="w-5 h-5 text-yellow-600 mt-0.5" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
                </svg>
              </div>
              <div>
                <h3 className="text-sm font-medium text-yellow-800">Medical Disclaimer</h3>
                <p className="text-sm text-yellow-700 mt-1">
                  This report is generated by AI analysis and should not replace professional medical advice. 
                  Please consult with a qualified dermatologist for proper diagnosis and treatment.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
